name: ParkourTimer
version: 1.1.1
main: com.earthpol.parkourtimer.ParkourTimer
api-version: 1.20

commands:
  parkour:
    description: Parkour commands
    usage: "/parkour <clear|leaderboard> [player]"